[tool.black]
include = '\.pyi?$'
line-length = 80
preview = true
fast = true

[tool.pyright]
typeCheckingMode = "off"
reportMissingImports = false

[project]
requires-python = ">=3.8"
name = "max-repo"

