[project]
name = "BERT C Torchscript"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max/", "pytorch"]
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]

[dependencies]
python = ">=3.9,<3.13"
max = "*"
networkx = "3.1"
transformers = ">=4.44.0"
numpy = "<2.0"
cmake = ">=3.24"

# For performance, prefer pytorch over anything else.
# The linux ARM package doesn't exist there, so prefer PyPi instead. 
[target.linux-64.dependencies]
pytorch = {version = "==2.4.1", channel = "pytorch"}
[target.osx-arm64.dependencies]
pytorch = {version = "==2.4.1", channel = "pytorch"}
[target.linux-aarch64.pypi-dependencies]
torch = "==2.4.1"
[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cpu"]
