[project]
name = "max-gui"
version = "0.1.0"
description = "Example of a GUI using MAX"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]

[tasks]
gui = "streamlit run home.py"

[dependencies]
streamlit = ">=1.35.0,<1.36"
psutil = ">=5.9.8,<5.10"
openai = ">=1.34.0,<1.35"
