[project]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "An example of extending a graph with a custom Mojo operation"
name = "Custom Operation - Addition"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
addition = { cmd="mojo package kernels/ -o kernels.mojopkg && python addition.py", env={ MODULAR_ONLY_USE_NEW_EXTENSIBILITY_API="true" }}
mandelbrot = { cmd="mojo package kernels/ -o kernels.mojopkg && python mandelbrot.py", env={ MODULAR_ONLY_USE_NEW_EXTENSIBILITY_API="true" }}

[dependencies]
python = ">=3.9,<3.13"
max = ">=24.6.0.dev2024090821"
