[project]
name = "Mojo Graph API Examples"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max/"]
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]

[tasks]
llama2 = "mojo run_pipeline.ðŸ”¥ llama2"
llama3 = "mojo run_pipeline.ðŸ”¥ llama3"
replit = "mojo run_pipeline.ðŸ”¥ replit"
quantize-tinystories = "mojo run_pipeline.ðŸ”¥ quantize-tinystories"
basic = "mojo basics/basic.ðŸ”¥"
inspect-guff = "mojo inspect-guff.ðŸ”¥"

[dependencies]
python = ">=3.9,<3.13"
huggingface_hub = ">=0.24.6,<0.25"
transformers = ">=4.44.2"
max = "*"
